export function useNewsArticle() {
  return [
    {
      title: 'VAMX Seminar Seires 1: Architecture',
      author: 'VAMX Community Team',
      profession: 'UCL Bartlett School of Architecture',
      img: '/imgs/Community/News/s1seminar/MainCover.jpg',
      tags: ['Academy'],
      href: '/community/news/vamxseminar_s1',
      level: 2,
      avatar: '/imgs/Community/Avatar/topverse.png',
      createTime: '2023/7/25',
    },
    {
      title: 'VAMX Academy: Bartlett RC-9',
      author: 'VAMX Community Team',
      profession: 'UCL Bartlett School of Architecture',
      img: '/imgs/Community/News/rc9/logo.png',
      tags: ['Academy'],
      href: '/community/news/rc9',
      level: 2,
      avatar: '/imgs/Community/Avatar/topverse.png',
      createTime: '2020/6/5',
    },
    {
      title: 'VAMX Master: Igor Pantic',
      author: 'VAMX Community Team',
      profession: 'Igor Pantic',
      img: '/imgs/Community/News/igorpantic/studiologo.png',
      tags: ['Member'],
      href: '/community/news/igorpantic',
      level: 2,
      avatar: '/imgs/Community/Avatar/topverse.png',
      createTime: '2020/6/5',
    },
    {
      title: 'VAMX Master: SoomeenHahm',
      author: 'VAMX Community Team',
      profession: 'Soomeen Hahm Design LTD.',
      img: '/imgs/Community/News/soomeenhahm/logo.png',
      tags: ['Member'],
      href: '/community/news/soomeenhahm',
      level: 2,
      avatar: '/imgs/Community/Avatar/topverse.png',
      createTime: '2020/6/5',
    },
    {
      title: 'VAMX Professional: ArchiPocket',
      author: 'VAMX Community Team',
      profession: 'ArchiPocket',
      img: '/imgs/Community/News/archipocket/001.png',
      tags: ['Member'],
      href: '/community/news/archipocket',
      level: 1,
      avatar: '/imgs/Community/Avatar/topverse.png',
      createTime: '2020/6/15',
    },
  ]
}
