export function useWeb3() {
  return {
    ending: 'Ajlksdjflajsd;lfja;ldf',
    head: {
      img: '/imgs/Project/Metaverse-Build/MusicVenue.jpg',
      topic: 'Never Drink Alone：The Bar Symphony',
      title: 'Metaverse Space Design',
      description: 'Award-Winning Project',
    },
    feature: {
      topic: 'home.sectionEight.topic',
      description: 'home.sectionEight.description',
      content: [
        {
          title: 'home.sectionEight.content.title[0]',
          description: 'home.sectionEight.content.topic[0]',
          icon: 'i-medical-icon-i-health-services',
        },
        {
          title: 'home.sectionEight.content.title[1]',
          description: 'home.sectionEight.content.topic[1]',
          icon: 'i-maki-college-11',
        },
        {
          title: 'home.sectionEight.content.title[2]',
          description: 'home.sectionEight.content.topic[2]',
          icon: 'i-maki-amusement-park-11',
        },
        {
          title: 'home.sectionEight.content.title[3]',
          description: 'home.sectionEight.content.topic[3]',
          icon: 'i-maki-gaming',
        },
        {
          title: 'home.sectionEight.content.title[4]',
          description: 'home.sectionEight.content.topic[4]',
          icon: 'i-maki-city',
        },
        {
          title: 'home.sectionEight.content.title[5]',
          description: 'home.sectionEight.content.topic[5]',
          icon: 'i-maki-basketball-11',
        },
        {
          title: 'home.sectionEight.content.title[6]',
          description: 'home.sectionEight.content.topic[6]',
          icon: 'i-maki-baseball-11',
        },
        {
          title: 'home.sectionEight.content.title[7]',
          description: 'home.sectionEight.content.topic[7]',
          icon: 'i-maki-communications-tower-11',
        },

      ],
    },
    solutions: {
      title: 'home.sectionFour.title',
      topic: 'home.sectionFour.topic',
      description: 'home.sectionFour.description',
      link: {
        name: 'home.sectionFour.link',
        href: '#',
      },
      content: [
        {
          title: 'TOPVERSE与UCL Bartlett第九研究室共同成立VAMX数研组',
          subtitle: 'VR/AR/MR/XR工程师、设计师与开发者开放学术社区',
          img: '/imgs/Release/vamxlaunch/008.png',
          tags: ['Mixed Reality'],
          href: '/release/vamxlaunch',
          author: 'Community Team',
          profession: 'TOPVERSE Shanghai Studio',
          avatar: '/imgs/Community/Avatar/topverse.png',
          createTime: '2023/6/6',
        },
        {
          title: 'TOPVERSE与UCL Bartlett第九研究室共同成立VAMX数研组',
          subtitle: 'VR/AR/MR/XR工程师、设计师与开发者开放学术社区',
          img: '/imgs/Release/vamxlaunch/008.png',
          tags: ['Mixed Reality'],
          href: '/release/vamxlaunch',
          author: 'Community Team',
          profession: 'TOPVERSE Shanghai Studio',
          avatar: '/imgs/Community/Avatar/topverse.png',
          createTime: '2023/6/6',
        },
        {
          title: 'TOPVERSE与UCL Bartlett第九研究室共同成立VAMX数研组',
          subtitle: 'VR/AR/MR/XR工程师、设计师与开发者开放学术社区',
          img: '/imgs/Release/vamxlaunch/008.png',
          tags: ['Mixed Reality'],
          href: '/release/vamxlaunch',
          author: 'Community Team',
          profession: 'TOPVERSE Shanghai Studio',
          avatar: '/imgs/Community/Avatar/topverse.png',
          createTime: '2023/6/6',
        },
        {
          title: '立“码”浸入新宇宙',
          subtitle: '全新VR游戏体验《樱花城》登录Meta Quest',
          img: '/imgs/Release/sakuracity/20230607-135223.jpg',
          tags: ['Web 3.0', 'Mixed Reality'],
          href: '/release/sakuracity',
          author: 'Technology Lab',
          profession: 'TOPVERSE Beijing Lab',
          avatar: '/imgs/Community/Avatar/topverse.png',
          createTime: '2023/6/6',
        },
        {
          title: 'TOPVERSE联合中国铁塔入围数字中国城市设计元宇宙RAR赛道百景新锐',
          subtitle: '2023数字中国创新大赛',
          img: '/imgs/Release/dcic2023/001.png',
          tags: ['Web 3.0', 'Digital Twins'],
          href: '/release/dcic2023',
          author: 'Technology Lab',
          profession: 'TOPVERSE Beijing Lab',
          avatar: '/imgs/Community/Avatar/topverse.png',
          createTime: '2023/04/21',
        },
        {
          title: '2022年度TOPVERSE高光时刻',
          subtitle: 'Annual Review',
          img: '/imgs/Release/2023annualreview/s00.jpg',
          tags: ['Web 3.0', 'Digital Twins'],
          href: '/release/annualreview2023',
          author: 'Technical Artist/ 3D Content Team',
          profession: 'TOPVERSE Shanghai Studio',
          avatar: '/imgs/Community/Avatar/topverse.png',
          createTime: '2022/1/18',
        },
      ],
    },
  }
}
