export function useWeb3() {
  return {
    ending: 'Ajlksdjflajsd;lfja;ldf',
    head: {
      img: '/imgs/Solutions/Web3/web3blockchainheader.png',
      topic: '互联网3.0内容及交互生态',
      title: '元宇宙空间及数字经济',
      description: '解决方案',
    },
    feature: {
      topic: 'home.sectionWeb3.topic',
      description: 'home.sectionWeb3.description',
      content: [
        {
          title: 'home.sectionWeb3.content.title[0]',
          description: 'home.sectionWeb3.content.topic[0]',
          icon: 'i-icomoon-free-500px',
        },
        {
          title: 'home.sectionWeb3.content.title[1]',
          description: 'home.sectionWeb3.content.topic[1]',
          icon: 'i-file-icons-3d-model',
        },
        {
          title: 'home.sectionWeb3.content.title[2]',
          description: 'home.sectionWeb3.content.topic[2]',
          icon: 'i-octicon-copilot-16',
        },
        {
          title: 'home.sectionWeb3.content.title[3]',
          description: 'home.sectionWeb3.content.topic[3]',
          icon: 'i-octicon-circuit-board',
        },
        {
          title: 'home.sectionWeb3.content.title[4]',
          description: 'home.sectionWeb3.content.topic[4]',
          icon: 'i-icomoon-free-dice',
        },
        {
          title: 'home.sectionWeb3.content.title[5]',
          description: 'home.sectionWeb3.content.topic[5]',
          icon: 'i-icon-park-solid-anchor-one',
        },
        {
          title: 'home.sectionWeb3.content.title[6]',
          description: 'home.sectionWeb3.content.topic[6]',
          icon: 'i-icon-park-solid-address-book',
        },
        {
          title: 'home.sectionWeb3.content.title[7]',
          description: 'home.sectionWeb3.content.topic[7]',
          icon: 'i-icomoon-free-barcode',
        },

      ],
    },
    solutions: {
      title: 'home.sectionWeb3.solutions.title',
      topic: 'home.sectionWeb3.solutions.topic',
      description: 'home.sectionWeb3.solutions.description',
      link: {
        name: 'home.sectionWeb3.solutions.link',
        href: '/release',
      },
      content: [
        {
          title: 'TOPVERSE与UCL Bartlett第九研究室共同成立VAMX数研组',
          subtitle: 'VR/AR/MR/XR工程师、设计师与开发者开放学术社区',
          img: '/imgs/Release/vamxlaunch/008.png',
          tags: ['Mixed Reality'],
          href: '/release/vamxlaunch',
          author: 'Community Team',
          profession: 'TOPVERSE Shanghai Studio',
          avatar: '/imgs/Community/Avatar/topverse.png',
          createTime: '2023/6/6',
        },
        {
          title: 'TOPVERSE与UCL Bartlett第九研究室共同成立VAMX数研组',
          subtitle: 'VR/AR/MR/XR工程师、设计师与开发者开放学术社区',
          img: '/imgs/Release/vamxlaunch/008.png',
          tags: ['Mixed Reality'],
          href: '/release/vamxlaunch',
          author: 'Community Team',
          profession: 'TOPVERSE Shanghai Studio',
          avatar: '/imgs/Community/Avatar/topverse.png',
          createTime: '2023/6/6',
        },
        {
          title: 'TOPVERSE与UCL Bartlett第九研究室共同成立VAMX数研组',
          subtitle: 'VR/AR/MR/XR工程师、设计师与开发者开放学术社区',
          img: '/imgs/Release/vamxlaunch/008.png',
          tags: ['Mixed Reality'],
          href: '/release/vamxlaunch',
          author: 'Community Team',
          profession: 'TOPVERSE Shanghai Studio',
          avatar: '/imgs/Community/Avatar/topverse.png',
          createTime: '2023/6/6',
        },
        {
          title: '立“码”浸入新宇宙',
          subtitle: '全新VR游戏体验《樱花城》登录Meta Quest',
          img: '/imgs/Release/sakuracity/20230607-135223.jpg',
          tags: ['Web 3.0', 'Mixed Reality'],
          href: '/release/sakuracity',
          author: 'Technology Lab',
          profession: 'TOPVERSE Beijing Lab',
          avatar: '/imgs/Community/Avatar/topverse.png',
          createTime: '2023/6/6',
        },
        {
          title: 'TOPVERSE联合中国铁塔入围数字中国城市设计元宇宙RAR赛道百景新锐',
          subtitle: '2023数字中国创新大赛',
          img: '/imgs/Release/dcic2023/001.png',
          tags: ['Web 3.0', 'Digital Twins'],
          href: '/release/dcic2023',
          author: 'Technology Lab',
          profession: 'TOPVERSE Beijing Lab',
          avatar: '/imgs/Community/Avatar/topverse.png',
          createTime: '2023/04/21',
        },
        {
          title: '2022年度TOPVERSE高光时刻',
          subtitle: 'Annual Review',
          img: '/imgs/Release/2023annualreview/s00.jpg',
          tags: ['Web 3.0', 'Digital Twins'],
          href: '/release/annualreview2023',
          author: 'Technical Artist/ 3D Content Team',
          profession: 'TOPVERSE Shanghai Studio',
          avatar: '/imgs/Community/Avatar/topverse.png',
          createTime: '2022/1/18',
        },
      ],
    },
  }
}
