export function useAIGC() {
  return {
    ending: 'home.sectionAIGC.ending',
    head: {
      img: '/imgs/Solutions/AIGC/AIGCheader.jpg',
      topic: '大模型驱动的生成式人工智能',
      title: '打造多模态内容创作及智慧管理模式',
      description: 'Multi-Model Artificial Intelligence Generated Contents',
    },
    feature: {
      topic: 'home.sectionAIGC.topic',
      description: 'home.sectionAIGC.description',
      content: [
        {
          title: 'home.sectionAIGC.content.title[0]',
          description: 'home.sectionAIGC.content.topic[0]',
          icon: 'i-akar-icons-slack-fill',
        },
        {
          title: 'home.sectionAIGC.content.title[1]',
          description: 'home.sectionAIGC.content.topic[1]',
          icon: 'i-akar-icons-vscode-fill',
        },
        {
          title: 'home.sectionAIGC.content.title[2]',
          description: 'home.sectionAIGC.content.topic[2]',
          icon: 'i-akar-icons-image',
        },
        {
          title: 'home.sectionAIGC.content.title[3]',
          description: 'home.sectionAIGC.content.topic[3]',
          icon: 'i-akar-icons-soundcloud-fill',
        },
        {
          title: 'home.sectionAIGC.content.title[4]',
          description: 'home.sectionAIGC.content.topic[4]',
          icon: 'i-akar-icons-game-controller',
        },
        {
          title: 'home.sectionAIGC.content.title[5]',
          description: 'home.sectionAIGC.content.topic[5]',
          icon: 'i-akar-icons-telescope',
        },
        {
          title: 'home.sectionAIGC.content.title[6]',
          description: 'home.sectionAIGC.content.topic[6]',
          icon: 'i-icon-park-solid-hold-seeds',
        },
        {
          title: 'home.sectionAIGC.content.title[7]',
          description: 'home.sectionAIGC.content.topic[7]',
          icon: 'i-akar-icons-language',
        },

      ],
    },
    solutions: {
      title: 'home.sectionAIGC.title',
      topic: 'home.sectionAIGC.topic',
      description: 'home.sectionAIGC.description',
      link: {
        name: 'home.sectionAIGC.link',
        href: '#',
      },
      content: [
        {
          title: 'TOPVERSE与UCL Bartlett第九研究室共同成立VAMX数研组',
          subtitle: 'VR/AR/MR/XR工程师、设计师与开发者开放学术社区',
          img: '/imgs/Release/vamxlaunch/008.png',
          tags: ['Mixed Reality'],
          href: '/release/vamxlaunch',
          author: 'Community Team',
          profession: 'TOPVERSE Shanghai Studio',
          avatar: '/imgs/Community/Avatar/topverse.png',
          createTime: '2023/6/6',
        },
        {
          title: 'TOPVERSE与UCL Bartlett第九研究室共同成立VAMX数研组',
          subtitle: 'VR/AR/MR/XR工程师、设计师与开发者开放学术社区',
          img: '/imgs/Release/vamxlaunch/008.png',
          tags: ['Mixed Reality'],
          href: '/release/vamxlaunch',
          author: 'Community Team',
          profession: 'TOPVERSE Shanghai Studio',
          avatar: '/imgs/Community/Avatar/topverse.png',
          createTime: '2023/6/6',
        },
        {
          title: 'TOPVERSE与UCL Bartlett第九研究室共同成立VAMX数研组',
          subtitle: 'VR/AR/MR/XR工程师、设计师与开发者开放学术社区',
          img: '/imgs/Release/vamxlaunch/008.png',
          tags: ['Mixed Reality'],
          href: '/release/vamxlaunch',
          author: 'Community Team',
          profession: 'TOPVERSE Shanghai Studio',
          avatar: '/imgs/Community/Avatar/topverse.png',
          createTime: '2023/6/6',
        },
        {
          title: '立“码”浸入新宇宙',
          subtitle: '全新VR游戏体验《樱花城》登录Meta Quest',
          img: '/imgs/Release/sakuracity/20230607-135223.jpg',
          tags: ['Web 3.0', 'Mixed Reality'],
          href: '/release/sakuracity',
          author: 'Technology Lab',
          profession: 'TOPVERSE Beijing Lab',
          avatar: '/imgs/Community/Avatar/topverse.png',
          createTime: '2023/6/6',
        },
        {
          title: 'TOPVERSE联合中国铁塔入围数字中国城市设计元宇宙RAR赛道百景新锐',
          subtitle: '2023数字中国创新大赛',
          img: '/imgs/Release/dcic2023/001.png',
          tags: ['Web 3.0', 'Digital Twins'],
          href: '/release/dcic2023',
          author: 'Technology Lab',
          profession: 'TOPVERSE Beijing Lab',
          avatar: '/imgs/Community/Avatar/topverse.png',
          createTime: '2023/04/21',
        },
        {
          title: '2022年度TOPVERSE高光时刻',
          subtitle: 'Annual Review',
          img: '/imgs/Release/2023annualreview/s00.jpg',
          tags: ['Web 3.0', 'Digital Twins'],
          href: '/release/annualreview2023',
          author: 'Technical Artist/ 3D Content Team',
          profession: 'TOPVERSE Shanghai Studio',
          avatar: '/imgs/Community/Avatar/topverse.png',
          createTime: '2022/1/18',
        },
      ],
    },
  }
}
