export function useCommunityArticle() {
  return [
    {
      title: 'Decor',
      subtitle: 'asdasdasfasfasfasfasfasfaf',
      author: 'Author',
      profession: 'Fine Art, Dining',
      img: '/imgs/Home-Stories/Circulus.jpg',
      tags: ['Web 3.0'],
      href: '/community/test',
      level: 0,
      avatar: '/imgs/Home-Stories/Circulus.jpg',
      createTime: '2023/6/5',
    },
    {
      title: 'Decor',
      author: 'Author',
      subtitle: 'asdasdasfasfasfasfasfasfaf',
      profession: 'Fine Art, Dining',
      img: '/imgs/Home-Stories/Circulus.jpg',
      tags: ['Web 3.0'],
      href: '/community/test',
      level: 1,
      avatar: '/imgs/Home-Stories/Circulus.jpg',
      createTime: '2023/6/5',
    },
    {
      title: 'Decor',
      author: 'Author',
      profession: 'Fine Art, Dining',
      img: '/imgs/Home-Stories/Circulus.jpg',
      tags: ['Web 3.0'],
      href: '/community/test',
      level: 2,
      avatar: '/imgs/Home-Stories/Circulus.jpg',
      createTime: '2023/6/5',
    },
    {
      title: 'Decor',
      author: 'Author',
      profession: 'Fine Art, Dining',
      img: '/imgs/Home-Stories/Circulus.jpg',
      tags: ['Web 3.0'],
      href: '/community/test',
      level: 0,
      avatar: '/imgs/Home-Stories/Circulus.jpg',
      createTime: '2023/6/5',
    },
  ]
}
