export function useCommunityArticle() {
  return [
    {
      title: 'MetaFold',
      author: 'Xin LU, Zeyuan Meng, Guanyu Shi, Jieni Zhang',
      profession: 'UCL Bartlett RC9 Project',
      img: '/imgs/Community/Project/metafold/001.png',
      tags: ['Project'],
      href: '/community/project/metafold',
      level: 2,
      avatar: '/imgs/Community/Avatar/bartlett.png',
      createTime: '2020/6/5',
    },
    {
      title: 'CeARamics',
      author: 'Jiaxiang Luo, Sarah Aldaboos, Efthymia Mastrokalou, Rahaf Aldabous',
      profession: 'UCL Bartlett RC9 Project',
      img: '/imgs/Community/Project/cearamics/001.png',
      tags: ['Project'],
      href: '/community/project/cearamics',
      level: 2,
      avatar: '/imgs/Community/Avatar/bartlett.png',
      createTime: '2020/6/5',
    },
    {
      title: 'reBENT',
      author: 'Xi He, Ziqi Song, Pablo Isaac Jaramillo Pazmino',
      profession: 'UCL Bartlett RC9 Project',
      img: '/imgs/Community/Project/rebent/001.png',
      tags: ['Project'],
      href: '/community/project/rebent',
      level: 2,
      avatar: '/imgs/Community/Avatar/bartlett.png',
      createTime: '2020/6/5',
    },
    {
      title: 'Steam.Me.Up',
      author: 'Chenfan Cai, Zixuan Fan, Yaxin Ding, Honghao Zhang',
      profession: 'UCL Bartlett RC9 Project',
      img: '/imgs/Community/Project/steammeup/001.png',
      tags: ['Project'],
      href: '/community/project/steammeup',
      level: 2,
      avatar: '/imgs/Community/Avatar/bartlett.png',
      createTime: '2020/6/5',
    },
    {
      title: 'Steampunk Pavilion',
      author: 'Gwyllim Jahn, Cameron Newnham, Soomeen Hahm, Igor Pantic',
      profession: 'Format Engineering (UK)',
      img: '/imgs/Community/Project/steampunk/190913+Steampunk+0135.jpg',
      tags: ['Project'],
      href: '/community/project/steampunkpavilion',
      level: 2,
      avatar: '/imgs/Community/Avatar/igorpantic.jpg',
      createTime: '2019/10/11',
    },
    {
      title: 'Reusable Augmented Concrete System: Accessible Method for Formwork Manufacturing through Holographic Guidance',
      author: 'Xin Lu, Zeyuan Meng, Alvaro Lopez Rodriguez, Igor Pantic',
      profession: 'UCL Bartlett RC9',
      img: '/imgs/Community/Publication/ecaade_reusableaugmentedconcretesystem.png',
      tags: ['Publication'],
      href: '/community/publication/ecaade_reusableformworksystem',
      level: 2,
      avatar: '/imgs/Community/Avatar/ecaade.png',
      createTime: '2020/7/30',
    },
    {
      title: 'Fabrication of Complex Clay Structures through an Augmented Reality Assisted Platform',
      author: 'Jiaxiang Luo, Efthymia Mastrokalou, Rahaf Aldabous, Sarah Aldaboos, Alvaro Lopez Rodriguez',
      profession: 'UCL Bartlett RC9',
      img: '/imgs/Community/Publication/caadria_cearamics.png',
      tags: ['Publication'],
      href: '/community/publication/caadria-fabricationofcomplexclaystructurethroughanaugmentedrealityassistedplatform',
      level: 2,
      avatar: '/imgs/Community/Avatar/caadria.png',
      createTime: '2022/6/18',
    },
  ]
}
