export function useCommunityArticle() {
  return [
    {
      title: 'MetaFold',
      author: 'Xin LU, Zeyuan Meng, Guanyu Shi, Jieni Zhang',
      profession: 'UCL Bartlett RC9 Project',
      img: '/imgs/Community/Project/metafold/001.png',
      tags: ['Mixed Reality'],
      href: '/community/project/metafold',
      level: 2,
      avatar: '/imgs/Community/Avatar/bartlett.png',
      createTime: '2020/6/5',
    },
    {
      title: 'CeARamics',
      author: 'Jiaxiang Luo, Sarah Aldaboos, Efthymia Mastrokalou, Rahaf Aldabous',
      profession: 'UCL Bartlett RC9 Project',
      img: '/imgs/Community/Project/cearamics/001.png',
      tags: ['Mixed Reality'],
      href: '/community/project/cearamics',
      level: 2,
      avatar: '/imgs/Community/Avatar/bartlett.png',
      createTime: '2020/6/5',
    },
    {
      title: 'reBENT',
      author: 'Xi He, Ziqi Song, Pablo Isaac Jaramillo Pazmino',
      profession: 'UCL Bartlett RC9 Project',
      img: '/imgs/Community/Project/rebent/001.png',
      tags: ['Mixed Reality'],
      href: '/community/project/rebent',
      level: 2,
      avatar: '/imgs/Community/Avatar/bartlett.png',
      createTime: '2020/6/5',
    },
    {
      title: 'Steam.Me.Up',
      author: 'Chenfan Cai, Zixuan Fan, Yaxin Ding, Honghao Zhang',
      profession: 'UCL Bartlett RC9 Project',
      img: '/imgs/Community/Project/steammeup/001.png',
      tags: ['Mixed Reality'],
      href: '/community/project/steammeup',
      level: 2,
      avatar: '/imgs/Community/Avatar/bartlett.png',
      createTime: '2020/6/5',
    },
    {
      title: 'Steampunk Pavilion',
      author: 'Gwyllim Jahn, Cameron Newnham, Soomeen Hahm, Igor Pantic',
      profession: 'Format Engineering (UK)',
      img: '/imgs/Community/Project/steampunk/190913+Steampunk+0135.jpg',
      tags: ['Mixed Reality'],
      href: '/community/project/steampunkpavilion',
      level: 2,
      avatar: '/imgs/Community/Avatar/igorpantic.jpg',
      createTime: '2019/10/11',
    },
  ]
}
