name: Gitea Actions Demo
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: [push]

jobs:
  Explore-Gitea-Actions:
    runs-on: server container:
    volumes:
      - /run/docker.sock:/run/docker.sock
    steps:
      - run: docker build --pull --rm -f "Dockerfile" -t website-v1:latest "."
      - run: docker rm -f website-v1 || true
      - run: docker run -d -p 19555:80 --restart=unless-stopped --name website-v1 website-v1
      - run: docker rmi $(docker images -f "dangling=true" -q) || true
      - run: docker ps
